### ISSUE TITLE
CudaText projects

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_file_type_profile#12]
@dinkumoil Andreas, i was thinking about making NEW project system in Cud, ie cloning (making copy) of VisualStudioCode project panel. maybe not all features. in Pascal code, not as plugin. it is big work so i cannot find time yet... if you are interested, in making it, let me know.

VSCode Explorer panel = combined TabsList + folder panel (one above the other, and one is autosized, other has the rest height).

**Comment by Alexey-T** [comment]
<img width="744" alt="vv" src="https://user-images.githubusercontent.com/4154978/70521478-5d9b1680-1b50-11ea-8867-d11e3752c0d3.png">

**Comment by dinkumoil** [comment]
Alexey, currently I'm very busy in my job. My company got a customer order to extend our main software product. There is a huge amount of work that has to be done. I work till late in the evenings and even at the weekends. So, I enjoy every minute to be off-keyboard. Thus I have to decline your request, sorry.
