### ISSUE TITLE
ini key names

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_file_type_profile#2]
keyFileExt     = 'fileExt'
keyFileExtList = 'fileExts'
keyEncoding    = 'encoding'
keyEolFormat = 'eolFormat'

will look better with _

keyFileExt     = 'file_ext'
keyFileExtList = 'file_exts'
keyEncoding    = 'encoding'
keyEolFormat = 'eol_format'

**Comment by Alexey-T** [comment]
Python has style with _ separator, not camelCaseNames.

**Comment by dinkumoil** [comment]
I will not fix that because the keys in the INI file are, well keys in a INI file and not Python code.
